# Generated by Django 4.1.7 on 2023-02-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_usd_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
