# Generated by Django 4.1.7 on 2023-02-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_coin_coin_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
